spring:
  application:
    name: kafka-demo

  profiles:
    active: dev

  kafka:
    bootstrap-servers: "192.168.5.13:9092"
    consumer:
      group-id: "kafkaDemo"
      auto-offset-reset: earliest
      client-id: eph-kafka-consumer
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      enable-auto-commit: true
      auto-commit-interval: 1000
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      client-id: eph-kafka-producer
      retries: 0


kafka:
  topic:
    topic1: kafka-topic
